# Amsterdam
edge-am:
- am02p01ic-ztde040408.example.com
- am02p01ic-ztde040409.example.com

# Ashburn
edge-dc:
- dc04p01ic-ztde020105.example.com
- dc04p00ic-ztde020106.example.com

# Atlanta
edge-at:
- at01p01ic-ztde011105.example.com
- at01p00ic-ztde011107.example.com

# Chicago
edge-ch:
- ch03p01ic-ztde011002.example.com
- ch03p01ic-ztde011004.example.com

# Dallas
edge-da:
- da06p01ic-ztde011004.example.com
- da06p00ic-ztde011005.example.com

# Denver
edge-de:
- de01p01ic-ztde010308.example.com
- de01p00ic-ztde010310.example.com

# Frankfurt
edge-fr:
- fr02p01ic-ztde011207.example.com
- fr02p00ic-ztde011210.example.com

# Hong Kong
edge-hk:
- hk02p01ic-ztde011036.example.com
- hk02p01ic-ztde011038.example.com

# London (Offline)
# edgde-lo:

# Los Angeles
edge-la:
- la02p01ic-ztde020512.example.com
- la02p01ic-ztde020514.example.com

# Miami
edge-mi:
- mi01p01ic-ztde030404.example.com
- mi01p01ic-ztde030405.example.com

# New York (Offline)
# edge-ny:

# San Jose (Offline)
# edge-sj:

# Seattle
edge-se:
- se03p00ic-ztde010504.example.com
- se03p00ic-ztde010506.example.com

# Singapore
edge-si:
- si03p01ic-ztde010304.example.com
- si03p01ic-ztde010306.example.com

# Sydney
edge-sy:
- sy02p00ic-ztde010305.example.com
- sy02p00ic-ztde010307.example.com

# Tokyo
edge-ty:
- ty03p01ic-ztde010304.example.com
- ty03p01ic-ztde010308.example.com
